### ISSUE TITLE
Any Error handling?

### ISSUE THREAD

**Issue by adoyle-h** [SBoudrias/grouped-queue#6]
```js
queue.add(function(cb) {
  DB.fetch().then(cb).catch(cb);
});
```

If catch invoked, will the queue be stopped?
It seems that there is no any error handling in the repo.

**Comment by SBoudrias** [comment]
grouped-queue currently only support the callback style, there's no support for promises built-in.

This should be added.

**Comment by adoyle-h** [comment]
```js
var Queue = require('grouped-queue');
var queue = new Queue();

queue.add(function(cb) {
  console.log('~~1');
  cb();
});

queue.add(function(cb) {
  cb(new Error());
});

queue.add(function(cb) {
  console.log('~~2');
  cb();
});
```

I expect that the third task should not be invoked, because the error has been thrown in second task.
But actually the output is

```
~~1
~~2
```

**Comment by SBoudrias** [comment]
Thinking about this further today, I'm actually not sure if throwing an error should stop the queue.

Tasks in the queue doesn't necessarily depends on each other. If something break the process, it should break hard and exit the program. Otherwise, I would assume it's safe to process the next task.

At most, we could return a promise from the `add` method to resolve/fail when the task is actually done running. But tasks in a queue failing seems like a common scenario we might not want to block. What do you think?

**Comment by adoyle-h** [comment]
I agree with you. This project is a queue. Each running task should not be affected by the failure of other tasks.
Thanks for your reply.
